import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontFamily: 'Helvetica',
        fontSize: 12,
        color: '#333',
    },
    header: {
        borderBottomWidth: 1,
        borderBottomColor: '#ddd',
        paddingBottom: 20,
        marginBottom: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    logo: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    receiptTitle: {
        fontSize: 16,
        color: '#666',
    },
    section: {
        marginBottom: 20,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    label: {
        width: 120,
        fontWeight: 'bold',
        color: '#666',
    },
    value: {
        flex: 1,
    },
    amount: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#16a34a', // Green-600
        marginTop: 10,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        borderTopWidth: 1,
        borderTopColor: '#ddd',
        paddingTop: 10,
        textAlign: 'center',
        fontSize: 10,
        color: '#999',
    },
});

interface ReceiptProps {
    payment: {
        id: string;
        amount: number;
        createdAt: Date;
        notes?: string | null;
        worker: {
            name: string;
            phone: string;
        };
    };
}

const ReceiptTemplate = ({ payment }: ReceiptProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.logo}>WorkProof</Text>
                <Text style={styles.receiptTitle}>Payment Receipt</Text>
            </View>

            {/* Transaction Details */}
            <View style={styles.section}>
                <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 10 }}>Transaction Details</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Receipt ID:</Text>
                    <Text style={styles.value}>{payment.id.slice(0, 8).toUpperCase()}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Date:</Text>
                    <Text style={styles.value}>
                        {payment.createdAt instanceof Date
                            ? payment.createdAt.toLocaleDateString()
                            : new Date(payment.createdAt).toLocaleDateString()}
                    </Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Amount Paid:</Text>
                    <Text style={[styles.value, styles.amount]}>₹{payment.amount.toFixed(2)}</Text>
                </View>
            </View>

            {/* Worker Details */}
            <View style={styles.section}>
                <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 10 }}>Worker Details</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Name:</Text>
                    <Text style={styles.value}>{payment.worker.name}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Phone:</Text>
                    <Text style={styles.value}>{payment.worker.phone}</Text>
                </View>
            </View>

            {/* Additional Info */}
            {payment.notes && (
                <View style={styles.section}>
                    <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 10 }}>Notes</Text>
                    <Text style={styles.value}>{payment.notes}</Text>
                </View>
            )}

            {/* Footer */}
            <View style={styles.footer}>
                <Text>Generated by WorkProof - Verifiable Digital Ledger</Text>
                <Text>This is a computer-generated receipt and requires no signature.</Text>
            </View>
        </Page>
    </Document>
);

export default ReceiptTemplate;
